---
# tasks file for neutron

- name: create neutron db
  command: mysql -e "CREATE DATABASE neutron"
  ignore_errors: yes

- name: Grant 1
  command: mysql -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY '{{ NEUTRON_DBPASS }}'"

- name: Grant 2
  command: mysql -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY '{{ NEUTRON_DBPASS }}'"

- name: Grant 3
  command: mysql -e "GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'{{ CONTROLLER }}' IDENTIFIED BY '{{ NEUTRON_DBPASS }}'"

- name: Flush Privileges
  command: mysql -e "FLUSH PRIVILEGES"

- name: check for has_neutron_setup confirmation file
  command: cat ~/.has_neutron_setup
  ignore_errors: yes
  register: neutron_setup_check

- name: Add Keystone service and endpoint
  script: roles/neutron/files/neutron.sh
  register: neutron_setup
  when: neutron_setup_check|failed

#- name: Add Keystone service and endpoint
#  command: "{{ item }}"
#  with_items:
#   - keystone user-create --name neutron --pass neutron --email {{ EMAIL }}
#   - keystone user-role-add --user neutron --tenant service --role admin
#   - keystone service-create --name neutron --type network --description "OpenStack Networking"
#   - ID=`keystone service-list | awk '/ network / {print $2}'` keystone endpoint-create --service-id $ID --publicurl http://{{ CONTROLLER }}:9696 --adminurl http://{{ CONTROLLER }}:9696 --internalurl http://{{ CONTROLLER }}:9696
#  environment: ENVIRONMENT

- name: Install Networking Components
  yum: pkg={{ item }} state=installed
  with_items:
   - openstack-neutron
   - openstack-neutron-ml2
   - python-neutronclient

- name: Configure Networking Server Components
  command: "{{ item }}"
  with_items:
   - openstack-config --set /etc/neutron/neutron.conf database connection mysql://neutron:{{ NEUTRON_DBPASS }}@{{ CONTROLLER }}/neutron
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT auth_strategy keystone
   - openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_uri http://{{ CONTROLLER }}:5000
   - openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_host {{ CONTROLLER }}
   - openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_protocol http
   - openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_port 35357
   - openstack-config --set /etc/neutron/neutron.conf keystone_authtoken admin_tenant_name service
   - openstack-config --set /etc/neutron/neutron.conf keystone_authtoken admin_user neutron
   - openstack-config --set /etc/neutron/neutron.conf keystone_authtoken admin_password {{ NEUTRON_ADMIN_PASS }}
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT rpc_backend neutron.openstack.common.rpc.impl_qpid
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT qpid_hostname {{ CONTROLLER }}
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT notify_nova_on_port_status_changes True
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT notify_nova_on_port_data_changes True
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT nova_url http://{{ CONTROLLER }}:8774/v2
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT nova_admin_username nova
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT nova_admin_tenant_id $(keystone tenant-list | awk '/ service / { print $2 }')
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT nova_admin_password {{ NOVA_ADMIN_PASS }}
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT nova_admin_auth_url http://{{ CONTROLLER }}:35357/v2.0
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT core_plugin ml2
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT service_plugins router
  environment: ENVIRONMENT

- name: Configure the Modular Layer 2 (ML2) plug-in
  command: "{{ item }}"
  with_items:
   - openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 type_drivers gre
   - openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 tenant_network_types gre
   - openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 mechanism_drivers openvswitch
   - openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_gre tunnel_id_ranges 1:1000
   - openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup firewall_driver neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver
   - openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup enable_security_group True

- name: Configure Compute to use Networking
  command: "{{ item }}"
  with_items:
   - openstack-config --set /etc/nova/nova.conf DEFAULT network_api_class nova.network.neutronv2.api.API
   - openstack-config --set /etc/nova/nova.conf DEFAULT neutron_url http://{{ CONTROLLER }}:9696
   - openstack-config --set /etc/nova/nova.conf DEFAULT neutron_auth_strategy keystone
   - openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_tenant_name service
   - openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_username neutron
   - openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_password neutron
   - openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_auth_url http://{{ CONTROLLER }}:35357/v2.0
   - openstack-config --set /etc/nova/nova.conf DEFAULT linuxnet_interface_driver nova.network.linux_net.LinuxOVSInterfaceDriver
   - openstack-config --set /etc/nova/nova.conf DEFAULT firewall_driver nova.virt.firewall.NoopFirewallDriver
   - openstack-config --set /etc/nova/nova.conf DEFAULT security_group_api neutron

- name: create sym link for ml2 plugin
  file: src=/etc/neutron/plugins/ml2/ml2_conf.ini dest=/etc/neutron/plugin.ini owner=root group=root state=link

- name: db fixes
  command: "{{ item }}"
  with_items:
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT core_plugin neutron.plugins.ml2.plugin.Ml2Plugin
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT service_plugins neutron.services.l3_router.l3_router_plugin.L3RouterPlugin

- name: db sync again
  command: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugin.ini upgrade head" neutron
  when: neutron_setup_check|failed

- name: restart nova services
  service: name={{ item }} state=restarted
  with_items:
   - openstack-nova-api
   - openstack-nova-scheduler
   - openstack-nova-conductor

- name: enable neutron server
  service: name=neutron-server state=started enabled=yes

- name: set has_neutron_setup confirmation file
  command: touch ~/.has_neutron_setup
  when: neutron_setup|success
