---
# tasks file for neutron-compute-node
- name: Edit /etc/sysctl.conf vars
  command: "{{ item }}"
  with_items:
   - sed -i 's/net.ipv4.conf.all.rp_filter=1/net.ipv4.conf.all.rp_filter=0/g' /etc/sysctl.conf
   - sed -i 's/net.ipv4.conf.default.rp_filter=1/net.ipv4.conf.default.rp_filter=0/g' /etc/sysctl.conf
   - sysctl -p

- name: Install neutron packages
  yum: pkg={{ item }} state=installed
  with_items:
   - openstack-neutron-ml2
   - openstack-neutron-openvswitch
#   - openstack-nova-network  # not sure if this is needed

- name: Configure network common components
  command: "{{ item }}"
  with_items:
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT auth_strategy keystone
   - openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_uri http://{{ CONTROLLER }}:5000
   - openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_host {{ CONTROLLER }}
   - openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_protocol http
   - openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_port 35357
   - openstack-config --set /etc/neutron/neutron.conf keystone_authtoken admin_tenant_name service
   - openstack-config --set /etc/neutron/neutron.conf keystone_authtoken admin_user neutron
   - openstack-config --set /etc/neutron/neutron.conf keystone_authtoken admin_password {{ NEUTRON_ADMIN_PASS }}
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT rpc_backend neutron.openstack.common.rpc.impl_qpid
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT qpid_hostname {{ CONTROLLER }}
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT core_plugin ml2
   - openstack-config --set /etc/neutron/neutron.conf DEFAULT service_plugins router

- name: Configure ML2 plugin
  command: "{{ item }}"
  with_items:
   - openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 type_drivers gre
   - openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 tenant_network_types gre
   - openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 mechanism_drivers openvswitch
   - openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_gre tunnel_id_ranges 1:1000
   - openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ovs local_ip {{ LOCAL_IP }}
   - openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ovs tunnel_type gre
   - openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ovs enable_tunneling True
   - openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup firewall_driver neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver
   - openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini securitygroup enable_security_group True

- name: Enable OVS service
  service: name=openvswitch enabled=yes state=started

- name: Create a bridge named br-int in OVS
  openvswitch_bridge: bridge=br-int state=present

- name: Configure compute to use networking
  command: "{{ item }}"
  with_items:
   - openstack-config --set /etc/nova/nova.conf DEFAULT network_api_class nova.network.neutronv2.api.API
   - openstack-config --set /etc/nova/nova.conf DEFAULT neutron_url http://{{ CONTROLLER }}:9696
   - openstack-config --set /etc/nova/nova.conf DEFAULT neutron_auth_strategy keystone
   - openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_tenant_name service
   - openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_username neutron
   - openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_password {{ NEUTRON_ADMIN_PASS }}
   - openstack-config --set /etc/nova/nova.conf DEFAULT neutron_admin_auth_url http://{{ CONTROLLER }}:35357/v2.0
   - openstack-config --set /etc/nova/nova.conf DEFAULT linuxnet_interface_driver nova.network.linux_net.LinuxOVSInterfaceDriver
   - openstack-config --set /etc/nova/nova.conf DEFAULT firewall_driver nova.virt.firewall.NoopFirewallDriver
   - openstack-config --set /etc/nova/nova.conf DEFAULT security_group_api neutron

- name: Create symlink for ML2 plugin
  file: src=/etc/neutron/plugins/ml2/ml2_conf.ini dest=/etc/neutron/plugin.ini owner=root group=root state=link

- name: Finalize install
  command: "{{ item }}"
  with_items:
   - cp /etc/init.d/neutron-openvswitch-agent /etc/init.d/neutron-openvswitch-agent.orig
   - sed -i 's,plugins/openvswitch/ovs_neutron_plugin.ini,plugin.ini,g' /etc/init.d/neutron-openvswitch-agent

- name: Restart nova compute
  service: name=openstack-nova-compute state=restarted

- name: Enable neutron OVS agent
  service: name=neutron-openvswitch-agent enabled=yes state=restarted
